server:
  port: 3344
yes: okok

spring:
  application:
    name:  cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: git@github.com:Kmild/springcloud-config-2023.2.16-.git          #GitHub上面的git仓库名字
          search-paths:
            - springcloud-config-2023.2.16-   #
      label: master # 读取分支



#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka

